import { ArrowUpRight, Check, Sparkles } from 'lucide-react';
import type { Deal, RosyState } from './types';
export const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export const date=(s:string)=>new Date(s).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'});
export const go=(path:string)=>{window.location.hash=path;};
export function Avatar({state='idle',size='small'}:{state?:RosyState;size?:'small'|'large'}){return <span className={`avatar ${size} ${state}`}><span className="avatar-portrait"><img src="/rosy.jpeg" alt="Rosy"/></span><span className="avatar-status">{state==='success'?<Check size={10}/>:null}</span></span>;}
export function RosyLabel({state='idle',label='Rosy'}:{state?:RosyState;label?:string}){return <div className="rosy-label"><Avatar state={state}/><div><strong>{label}</strong><span className="rosy-state">{state==='idle'?'Your deal intelligence partner':state==='success'?'Memory updated':state==='analyzing'?'Retrieving relevant memories':state==='learning'?'Learning from this outcome':state==='insight'?'A relevant pattern found':'Grounded in customer evidence'}</span></div></div>;}
export function RiskBadge({risk}:{risk:Deal['risk']}){return <span className={`badge risk-${risk.toLowerCase()}`}><i/>{risk} risk</span>;}
export function Company({deal}:{deal:Deal}){return <span className="company"><span className="company-mark" style={{background:deal.color}}>{deal.initials}</span><span><strong>{deal.company}</strong><small>{deal.customer} · {deal.role}</small></span></span>;}
export function DealTable({deals}:{deals:Deal[]}){return <div className="table-wrap"><table><thead><tr><th>Company / champion</th><th>Deal value</th><th>Stage</th><th>Health</th><th>Risk</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{deals.map((d,i)=><tr key={d.id} style={{animationDelay:`${i*35}ms`}}><td><button className="company-button" onClick={()=>go(`/deals/${d.id}`)}><Company deal={d}/><span className="row-context">{d.recommendation}</span></button></td><td><strong>{money(d.value)}</strong><small>{d.probability}% probability</small></td><td><span className="stage">{d.stage}</span><small>Last touch {date(d.lastInteraction)}</small></td><td><span className="health-mini"><span style={{width:`${d.health}%`,background:d.health<60?'#c27750':'#2a7660'}}/></span><span>{d.health}<span className="muted"> / 100</span></span></td><td><RiskBadge risk={d.risk}/></td><td><button className="icon-button" aria-label={`Open ${d.company}`} onClick={()=>go(`/deals/${d.id}`)}><ArrowUpRight size={18}/></button></td></tr>)}</tbody></table></div>;}
export function Empty({title='No deals match your filters',body='Try another search or clear the filters.'}:{title?:string;body?:string}){return <div className="empty"><Sparkles size={28}/><h3>{title}</h3><p>{body}</p></div>;}
export function Loading(){return <div className="loading" role="status"><span className="spinner"/>Loading your workspace…</div>;}
