import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, CheckCheck, ChevronDown, ChevronRight, CircleAlert, FileText, Mail, MessageSquare, Network, Phone, Sparkles, X } from 'lucide-react';
import { dealService } from './services';
import type { Action, Deal, HealthFactor, Interaction, Memory, Outcome, OutcomeKind, Recommendation, RosyState, Stage } from './types';
import { Avatar, date, go, Loading, money, RiskBadge, RosyLabel } from './components';
interface Bundle { deal:Deal; interactions:Interaction[]; memories:Memory[]; recommendation:Recommendation; health:HealthFactor[] }
const scrollTo=(selector:string)=>document.querySelector(selector)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});
export default function DealDetail({id:routeId,onChange}:{id:string;onChange:()=>Promise<void>}){
 const [id,params]=routeId.split('?'); const initialMemory=new URLSearchParams(params).get('memory');
 const [b,setB]=useState<Bundle|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[selected,setSelected]=useState<string|null>(initialMemory),[event,setEvent]=useState<string|null>(null),[factor,setFactor]=useState(0),[rationale,setRationale]=useState(true),[rosy,setRosy]=useState<RosyState>('analyzing'),[action,setAction]=useState<Action|null>(null),[outcome,setOutcome]=useState<Outcome|null>(null),[modal,setModal]=useState<'action'|'outcome'|null>(null),[description,setDescription]=useState(''),[kind,setKind]=useState<OutcomeKind>('Meeting booked'),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[savingStage,setSavingStage]=useState(false),[formError,setFormError]=useState(''),[progress,setProgress]=useState(0),[toast,setToast]=useState('');
 const alive=useRef(true),trigger=useRef<HTMLButtonElement|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;if(timer.current)clearTimeout(timer.current);};},[]);
 async function fetchBundle():Promise<Bundle>{const [deal,interactions,memories,recommendation,health]=await Promise.all([dealService.getDeal(id),dealService.getInteractions(id),dealService.getMemories(id),dealService.getRosyRecommendation(id),dealService.getDealHealth(id)]);return{deal,interactions,memories,recommendation,health};}
 useEffect(()=>{let cancelled=false;setError('');setB(null);setRosy('analyzing');fetchBundle().then(data=>{if(!cancelled){setB(data);if(initialMemory){setEvent(data.memories.find(m=>m.id===initialMemory)?.interactionId||null);setProgress(2);}setRosy('insight');}}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[id,retry]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);},[toast]);
 function selectMemory(m:Memory){if(timer.current)clearTimeout(timer.current);setSelected(m.id);setEvent(m.interactionId);setProgress(2);setRosy('analyzing');timer.current=setTimeout(()=>setRosy('recommendation'),650);}
 function open(type:'action'|'outcome',e:React.MouseEvent<HTMLButtonElement>){trigger.current=e.currentTarget;setModal(type);setFormError('');if(type==='action')setDescription(b?.recommendation.summary||'');}
 function close(){if(busy)return;setModal(null);setTimeout(()=>trigger.current?.focus(),0);}
 async function submit(e:React.FormEvent){e.preventDefault();if(!b||busy)return;setBusy(true);setFormError('');try{if(modal==='action'){const a=await dealService.recordAction({dealId:id,recommendationId:b.recommendation.id,description:description.trim()});const updated=await fetchBundle();if(!alive.current)return;setAction(a);setB(updated);setProgress(4);setRosy('recommendation');setModal(null);setToast('Action recorded. Add the customer’s outcome when it is known.');setTimeout(()=>document.querySelector<HTMLButtonElement>('[data-outcome]')?.focus(),0);}else if(action){const o=outcome||await dealService.recordOutcome({actionId:action.id,dealId:id,kind,notes:notes.trim()});if(!alive.current)return;setOutcome(o);setRosy('learning');setProgress(5);await new Promise(r=>setTimeout(r,650));const m=await dealService.updateMemory(o.id);const updated=await fetchBundle();await onChange();if(!alive.current)return;setB(updated);setSelected(m.id);setEvent(m.interactionId);setProgress(6);setRosy('success');setModal(null);setToast('Rosy learned. The new memory now supports your next recommendation.');setTimeout(()=>document.querySelector<HTMLElement>('.learning-result')?.focus(),0);}}catch(e){if(alive.current)setFormError(e instanceof Error?e.message:'Could not save. Please retry.');}finally{if(alive.current)setBusy(false);}}
 async function changeStage(stage:Stage){if(!b||savingStage)return;setSavingStage(true);try{const deal=await dealService.updateDealStage(id,stage);if(alive.current){setB({...b,deal});setToast(`Deal moved to ${stage}.`);}await onChange();}catch(e){setToast(e instanceof Error?e.message:'Could not update stage.');}finally{if(alive.current)setSavingStage(false);}}
 if(error)return <div className="error" role="alert"><CircleAlert/><h1>We couldn’t open this deal</h1><p>{error}</p><div className="button-row"><button className="secondary" onClick={()=>go('/deals')}>Back to deals</button><button className="primary" onClick={()=>setRetry(retry+1)}>Try again</button></div></div>;
 if(!b)return <><RosyLabel state="analyzing" label="Connecting the customer context"/><Loading/></>;
 const {deal,interactions,memories,recommendation,health}=b, memory=memories.find(m=>m.id===selected),source=interactions.find(i=>i.id===memory?.interactionId),learned=memories.find(m=>m.isNew);const currentLearned=outcome&&memories.some(m=>m.interactionId===outcome.id);
 return <><button className="back-link" onClick={()=>go('/deals')}><ArrowLeft size={15}/>Back to deals</button><div className="deal-title"><div><span className="eyebrow">DEAL INTELLIGENCE WORKSPACE</span><div className="deal-name"><span className="company-mark" style={{background:deal.color}}>{deal.initials}</span><h1>{deal.company}</h1><RiskBadge risk={deal.risk}/></div><p>{deal.industry} <span>·</span> {deal.customer}, {deal.role}</p></div><div className="deal-value"><strong>{money(deal.value)}</strong><span>Annual deal value · closes {date(deal.closeDate)}</span></div></div>
 <div className="deal-meta"><div><span>DEAL STAGE</span><select aria-label="Change deal stage" value={deal.stage} disabled={savingStage} onChange={e=>changeStage(e.target.value as Stage)}>{['Discovery','Evaluation','Proposal','Negotiation','Closed won'].map(s=><option key={s}>{s}</option>)}</select></div><div><span>WIN PROBABILITY</span><strong>{deal.probability}% <small>From DealMind when available</small></strong></div><div><span>LAST REFRESH</span><strong>{date(deal.lastInteraction)} <small>Live API</small></strong></div><div><span>ALTERNATIVE</span><strong>{deal.competitor}</strong></div></div>
 <section className="intelligence-banner"><RosyLabel state={rosy} label={rosy==='success'?'A new outcome. A more informed next move.':recommendation.title}/><span className="grounded-label"><Network size={14}/>{recommendation.memoryIds.length} supporting memories</span></section>
 <div className="intelligence-path" aria-label="Intelligence flow">{['Context','Memory','Evidence','Recommendation','Action','Outcome','Learning'].map((s,i)=><span key={s} className={`${progress===i?'current':''} ${progress>i?'complete':''}`}><span>{progress>i?<Check size={12}/>:String(i+1).padStart(2,'0')}</span>{s}{i<6&&<ChevronRight size={15}/>}</span>)}</div>
 {learned&&<section className="learning-result" tabIndex={-1}><span className="learned-icon"><CheckCheck size={23}/></span><div><span className="eyebrow">ROSY LEARNED · MEMORY RETURNED BY DEALMIND</span><h2>{learned.title}</h2><p>{learned.learned}</p><p><strong>Next time:</strong> {learned.relevance}</p></div></section>}
 <div className="deal-workspace"><div className="deal-main"><section className="memory-workbench panel"><div className="section-heading"><div><span className="eyebrow">THE CONTEXT BEHIND THE NEXT MOVE</span><h2><Network size={20}/> Hindsight Memory <span className="count">{memories.length}</span></h2><p>Select a memory. Follow the evidence.</p></div><span className="connected-badge">Connected to this deal</span></div><div className="memory-map"><div className="deal-root"><span className="company-mark" style={{background:deal.color}}>{deal.initials}</span><div><small>CURRENT DEAL</small><strong>{deal.company}</strong></div></div><div className="memory-nodes">{memories.map((m,i)=><button key={m.id} className={`memory-node ${selected===m.id?'selected':''} ${m.isNew?'new-memory':''}`} aria-pressed={selected===m.id} aria-controls="memory-evidence" onClick={()=>selectMemory(m)} style={{animationDelay:`${i*45}ms`}}><span className="node-connector"/><span className="memory-node-icon">{m.isNew?<CheckCheck size={16}/>:<Network size={16}/>}</span><span><small>{m.isNew?'NEW LEARNING':m.category.toUpperCase()}</small><strong>{m.title}</strong><span>{date(m.date)} · {interactions.find(e=>e.id===m.interactionId)?.type||'Interaction'}</span></span><ChevronRight size={17}/></button>)}</div></div>
 <div id="memory-evidence" className={`evidence-panel ${memory?'expanded':''}`} key={memory?.id||'empty'}>{memory&&source?<><div className="evidence-head"><span className="eyebrow"><FileText size={14}/> BACKEND EVIDENCE</span><span>{source.type} · {date(source.date)}</span></div><blockquote>“{source.content}”<cite>— {source.person}</cite></blockquote><div className="evidence-grid"><div><small>MEMORY_USED</small><p>{memory.learned}</p></div><div><small>WHY IT MATTERS NOW</small><p>{memory.relevance}</p></div></div><button className="text-button" onClick={()=>{setEvent(source.id);scrollTo(`#event-${source.id}`);document.getElementById(`event-button-${source.id}`)?.focus({preventScroll:true});}}>View source in timeline <ArrowRight size={15}/></button></>:<div className="evidence-placeholder"><Network size={20}/><p>{memories.length?'Choose a memory above to inspect the evidence DealMind returned.':'DealMind has not returned memory_used for this deal yet. Retry after the backend has enough interaction history.'}</p></div>}</div><div className="memory-destination"><Network size={15}/><span>{memory&&recommendation.memoryIds.includes(memory.id)?'Selected evidence informs the recommendation':'Customer context informs Rosy’s next move'}</span><ArrowRight size={15}/></div></section>
 <section className="panel timeline-panel"><div className="section-heading"><div><h2>Customer story</h2><p>Every interaction, with its context intact.</p></div><span className="count">{interactions.length} events</span></div><div className="timeline">{[...interactions].reverse().map(i=>{const m=memories.find(m=>m.interactionId===i.id),Icon=i.type==='Email'?Mail:i.type==='Call'?Phone:i.type==='Outcome'?CheckCheck:i.type==='Action'?Check:MessageSquare;return <div key={i.id} id={`event-${i.id}`} className={`timeline-event ${event===i.id?'selected':''}`}><span className="timeline-icon"><Icon size={17}/></span><button id={`event-button-${i.id}`} className="timeline-button" aria-expanded={event===i.id} onClick={()=>{setEvent(event===i.id?null:i.id);setSelected(m?.id||null);if(m)setProgress(2);}}><span><small>{date(i.date)} · {i.type}</small><strong>{i.title}</strong><span>{i.person}{m&&<em><Network size={12}/>Linked memory</em>}</span></span><ChevronDown size={16}/></button>{event===i.id&&<div className="timeline-expanded"><p>{i.content}</p>{m&&<button className="text-button" onClick={()=>{selectMemory(m);scrollTo('.memory-workbench');}}>Explore related memory <ArrowUpRight size={14}/></button>}</div>}</div>;})}</div></section>
 </div><aside className="deal-side"><section className={`recommendation-panel ${memory&&recommendation.memoryIds.includes(memory.id)?'evidence-linked':''}`}><div className="recommendation-header"><Avatar state={rosy}/><div><span className="eyebrow">ROSY ANSWER</span><span className="confidence" title="Returned only when the backend includes confidence or score.">{recommendation.confidence}% confidence</span></div><Sparkles size={19}/></div><h2>{recommendation.title}</h2><p>{recommendation.summary}</p><button className="rationale-toggle" aria-expanded={rationale} onClick={()=>{setRationale(!rationale);setProgress(3);setRosy('recommendation');}}>Why this recommendation? <ChevronDown size={16} className={rationale?'rotated':''}/></button>{rationale&&<div className="rationale"><ul>{recommendation.rationale.map(r=><li key={r}><Check size={14}/>{r}</li>)}</ul><small>MEMORY_USED BY ROSY</small><div className="evidence-chips">{recommendation.memoryIds.length?recommendation.memoryIds.map(mid=>{const m=memories.find(m=>m.id===mid);return m?<button className={selected===m.id?'active':''} key={mid} onClick={()=>{selectMemory(m);scrollTo('.memory-workbench');}}><Network size={12}/>{m.category}</button>:null;}):<span className="no-evidence-chip">No memory_used returned</span>}</div></div>}
 <div className="action-section">{!action?<><button className="primary full-width" onClick={e=>open('action',e)}>{recommendation.actionLabel}<ArrowRight size={16}/></button><small>Records a seller action through the approved DealMind interactions endpoint.</small></>:!currentLearned?<><div className="action-done"><Check size={16}/>Action recorded</div><button data-outcome className="primary full-width" onClick={e=>open('outcome',e)}>Record customer outcome <ArrowRight size={16}/></button></>:<><div className="action-done"><CheckCheck size={17}/>Outcome connected to memory</div><button className="secondary full-width" onClick={()=>{setAction(null);setOutcome(null);setNotes('');setProgress(3);setRosy('recommendation');}}>Start next action <ArrowRight size={16}/></button></>}</div></section>
 <section className="panel health-panel"><div className="section-heading"><div><h2>Deal health</h2><p>Explore the factors behind the score.</p></div><div className={`health-score ${deal.health<60?'at-risk':''}`}>{deal.health}<small>/ 100</small></div></div><div className="health-factors">{health.map((h,i)=><button key={h.name} aria-pressed={factor===i} className={factor===i?'active':''} onClick={()=>setFactor(i)}><span>{h.name}<b>{h.score}</b></span><span className="factor-bar"><span style={{width:`${h.score}%`,background:h.score<50?'#b58058':'#64886a'}}/></span></button>)}</div><div className="health-evidence" key={factor}><small>SUPPORTING EVIDENCE</small><p>{health[factor].evidence}</p><button className="text-button" onClick={()=>{setEvent(health[factor].interactionId);setSelected(memories.find(m=>m.interactionId===health[factor].interactionId)?.id||null);scrollTo(`#event-${health[factor].interactionId}`);}}>View interaction <ArrowUpRight size={14}/></button></div></section>
 <section className="risk-note"><CircleAlert size={18}/><div><h3>Open blocker</h3><p>{deal.objection}</p><span>Alternative returned by backend: <strong>{deal.competitor}</strong></span></div></section></aside></div>
 <div className="toast" role="status" aria-live="polite">{toast&&<span><Check size={16}/>{toast}</span>}</div>
 {modal&&<div className="modal-backdrop" onClick={close}><section className="dialog outcome-dialog" role="dialog" aria-modal="true" aria-labelledby="action-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const els=e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),textarea:not(:disabled),select:not(:disabled)');if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els[els.length-1].focus();}else if(!e.shiftKey&&document.activeElement===els[els.length-1]){e.preventDefault();els[0].focus();}}}}><button className="dialog-close icon-button" aria-label="Close dialog" disabled={busy} onClick={close}><X size={20}/></button><RosyLabel state={busy&&modal==='outcome'?'learning':'idle'} label={modal==='action'?'From recommendation to action':'Every outcome is something to learn from'}/><h2 id="action-title">{modal==='action'?'Record your completed action':'What happened next?'}</h2><p className="dialog-subtitle">{deal.company} · {deal.customer}</p><form onSubmit={submit}>{modal==='action'?<label className="field">Action taken<textarea autoFocus required maxLength={2000} rows={4} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the action you completed…"/></label>:<><label className="field">Customer outcome<select autoFocus value={kind} disabled={!!outcome||busy} onChange={e=>setKind(e.target.value as OutcomeKind)}>{['Meeting booked','Positive reply','No response','Objection remains'].map(s=><option key={s}>{s}</option>)}</select></label><label className="field">Additional context <span className="optional">(optional)</span><textarea maxLength={2000} rows={3} value={notes} disabled={!!outcome||busy} onChange={e=>setNotes(e.target.value)} placeholder="What did the customer say? What should Rosy remember?"/></label><div className="learning-preview"><Network size={18}/><span>This outcome is sent to DealMind through POST /api/deals/{'{deal_id}'}/interactions, then intelligence is refreshed.</span></div></>}{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="button-row"><button type="button" className="secondary" disabled={busy} onClick={close}>Cancel</button><button type="submit" className="primary" disabled={busy||(modal==='action'&&!description.trim())}>{busy?<><span className="button-spinner"/>{modal==='action'?'Recording…':'Rosy is learning…'}</>:modal==='action'?<>Record action <Check size={16}/></>:<>Save outcome & refresh intelligence <Sparkles size={16}/></>}</button></div><p className="form-disclaimer">No backend outside the approved DealMind API is called.</p></form></section></div>}
 </>;
}
